config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :items do
    get :top_items, on: :collection
  end

  resources :restaurants

  resources :categories do
    resources :items, only: %i[add_item delete_item] do
      member do
        post :add_item
        delete :delete_item
      end
    end
  end

  resource :carts, only: %i[show destroy] do
    resource :cart_items, only: %i[add_quantity reduce_quantity] do
      post :add_quantity
      post :reduce_quantity
      post :remove_item
      post :clear_cart
    end
  end

  resources :orders, except: %i[destroy] do
    resources :order_items, only: %i[add_item] do
      post :add_item
    end
  end

  root 'items#index'

  # api

  namespace :api do
    namespace :v1 do
      resources :items, only: %i[index show]
      resources :restaurants, only: %i[index]
      resources :categories, only: %i[index]
      resources :orders, only: %i[index]
    end
  end
end

app/models/cart.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: carts
#
#  id         :bigint           not null, primary key
#  user_id    :bigint
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def show
    @cart = user_signed_in? ? @current_cart : Item.find(session[:cart_id])
  end

  def destroy
    @current_cart.destroy
    session[:cart_id].clear
    redirect_to root_path
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
  def calculate_item_quantaty(id)
    session[:cart_id].count(id)
  end

  def calculate_item_total_guest(id, price)
    session[:cart_id].count(id) * price
  end

  def calculate_guest_total(cart)
    cart.sum { |item| calculate_item_total_guest(item.id, item.price) }
  end
end

app/views/carts/_cart_item.html.erb
<tr>
  <td><%= cart_item.item.title %></td>
  <td>$<%= cart_item.item.price %></td>
  <td><%= cart_item.quantity %></td>
  <td><%= button_to '+', add_quantity_carts_cart_items_path(item_id: cart_item.item.id), class:"btn btn-dark" %></td>
  <td><%= button_to '-', reduce_quantity_carts_cart_items_path(item_id: cart_item.item.id), class:"btn btn-dark" %></td>
  <td><%= button_to 'Remove', remove_item_carts_cart_items_path(item_id: cart_item.item.id), class:"btn btn-dark" %></td>
  <td>$<%= calculate_item_total(cart_item) %></td>
</tr>

app/views/carts/_table.html.erb
<div class="container">
  <table class="table text-center">
    <thead class="thead-dark">
      <tr>
        <th>Title</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Increase</th>
        <th>Decrease</th>
        <th>Remove</th>
        <th>Subtotal</th>
      </tr>
    </thead>
    <tbody>
      <% if cart.items.count == 0%>
        <tr>
          <td><strong>No Items At the moment</strong></td>
        </tr>
      <% else %>
        <%= render partial: "cart_item", collection: cart.cart_items %>
      <% end %>
    </tbody>
    <tfoot>
      <td>
        <% if cart.cart_items.count != 0 %>
          <%= button_to 'Clear Cart', clear_cart_carts_cart_items_path, class:"btn btn-dark" %>
        <% end %>
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        <strong>Total</strong>
      </td>
      <td>$<%= calculate_total(cart.cart_items) %></td>
    </tfoot>
  </table>
</div>

app/views/carts/_table2.html.erb
<div class="container">
  <table class="table text-center">
    <thead class="thead-dark">
      <tr>
        <th>Title</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Increase</th>
        <th>Decrease</th>
        <th>Remove</th>
        <th>Subtotal</th>
      </tr>
    </thead>
    <tbody>
      <% if cart.count == 0%>
        <tr>
          <td><strong>No Items At the moment</strong></td>
        </tr>
      <% else %>
        <% cart.each do |item| %>
          <tr>
            <td><%= item.title  %></td>
            <td>$<%= item.price  %></td>
            <td><%= calculate_item_quantaty(item.id)  %></td>
            <td><%= button_to '+', add_quantity_carts_cart_items_path(item_id: item.id), class:"btn btn-dark" %></td>
            <td><%= button_to '-', reduce_quantity_carts_cart_items_path(item_id: item.id), class:"btn btn-dark" %></td>
            <td><%= button_to 'Remove', remove_item_carts_cart_items_path(item_id: item.id), class:"btn btn-dark" %></td>
            <td>$<%= calculate_item_total_guest(item.id, item.price) %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
    <tfoot>
      <td>
        <% if cart.count != 0 %>
          <%= button_to 'Clear Cart', clear_cart_carts_cart_items_path, class:"btn btn-dark" %>
        <% end %>
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        <strong>Total</strong>
      </td>
      <td>$<%= calculate_guest_total(cart) %></td>
    </tfoot>
  </table>
</div>

app/views/carts/show.html.erb
<h2>Cart</h2>
<% if user_signed_in? %>
  <%= render 'table', cart: @cart %>
  <%= link_to 'Back', root_path, class:"btn btn-dark"%>
  <% if @cart.cart_items.count != 0 %>
    <%= link_to 'Check Out', new_order_path, class:"btn btn-dark"%>
  <% end %>
<% else %>
  <%= render 'table2', cart: @cart %>
  <div class="row pt-3">
    <div class="col-sm-2h pt-2">
      <p><strong>Sign Up / In to Checkout</strong></p>
    </div>
    <div class="col-sm-2">
      <%= link_to 'Sign In', new_user_session_path, class: "btn btn-dark" %>
    </div>
  </div>
<% end %>