config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :items do
    get :top_items, on: :collection
  end

  resources :restaurants

  resources :categories do
    resources :items, only: %i[add_item delete_item] do
      member do
        post :add_item
        delete :delete_item
      end
    end
  end

  resource :carts, only: %i[show destroy] do
    resource :cart_items, only: %i[add_quantity reduce_quantity] do
      post :add_quantity
      post :reduce_quantity
      post :remove_item
      post :clear_cart
    end
  end

  resources :orders, except: %i[destroy] do
    resources :order_items, only: %i[add_item] do
      post :add_item
    end
  end

  root 'items#index'

  # api

  namespace :api do
    namespace :v1 do
      resources :items, only: %i[index show]
      resources :restaurants, only: %i[index]
      resources :categories, only: %i[index]
      resources :orders, only: %i[index]
    end
  end
end

app/models/restaurant.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: restaurants
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Restaurant < ApplicationRecord
  has_many :restaurant_items, dependent: :destroy
  has_many :items, through: :restaurant_items, dependent: :destroy

  validates :title, presence: true, uniqueness: true
end

app/controllers/api/v1/restaurants_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class RestaurantsController < Api::V1::BaseController
      def index
        @restaurants = Restaurant.all
        render json: @restaurants
      end
    end
  end
end

app/controllers/restaurants_controller.rb
# frozen_string_literal: true

class RestaurantsController < ApplicationController
  before_action :find_restaurant, except: %i[index new create]
  def index
    @restaurants = Restaurant.all
    authorize @restaurants
  end

  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def show; end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    authorize @restaurant
    if @restaurant.save
      flash[:notice] = 'Restaurant was successfully created'
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = 'Restaurant was successfully updated'
      redirect_to restaurants_path
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:title)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end
end

app/helpers/restaurants_helper.rb
# frozen_string_literal: true

module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: @restaurant, local: true) do |form| %>

  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize( @restaurant.errors.count, "error" ) %> prohibited this Restaurant from being saved:
      </h2>

      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group pb-2">
    <%= form.text_field :title, class:"form-control", placeholder: 'Title', required: true %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-dark " %>
  </div>

<% end %>

app/views/restaurants/_restaurant.html.erb
<tr>
  <td><%= restaurant.title %></td>
  <td><%= link_to 'Show Items', restaurant_path(restaurant), class:"btn btn-dark" %></td>
  <% if current_user.admin? %>
    <td><%= restaurant.items.count %></td>
    <td><%= link_to 'Edit Restaurant', edit_restaurant_path(restaurant), class:"btn btn-dark" %></td>
    <td><%= link_to 'Delete Restaurant', restaurant, method: :delete,
    data: { confirm: 'Are you sure?' } , class:"btn btn-dark" %></td>
  <% end %>
</tr>

app/views/restaurants/_table.html.erb
<div class="container">
  <table class="table text-center">
    <thead class="thead-dark">
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Price</th>
        <% if current_user.admin? %>
          <th>Status</th>
        <% end %>
        <th>Show</th>
        <% if current_user.admin? %>
          <th>Edit</th>
          <th>Delete</th>
        <% end %>
      </tr>
    </thead>
    <%= render 'table2', restaurant: @restaurant%>
  </table>
</div>

app/views/restaurants/_table2.html.erb
<% if current_user.admin? %>
  <tbody>
    <% restaurant.items.each do |item| %>
      <tr>
          <td><%= item.title %></td>
          <td><%= item.description %></td>
          <td>$<%= item.price %></td>
          <td><%= item.status %></td>
          <td><%= link_to 'Show Item', item_path(item), class:"btn btn-dark" %></td>
          <td><%= link_to 'Edit Item', edit_item_path(item, restaurant_id: restaurant), class:"btn btn-dark" %></td>
          <td><%= link_to 'Delete', item, method: :delete,
          data: { confirm: 'Are you sure?' } , class:"btn btn-dark" %></td>
      </tr>
    <% end %>
  </tbody>
<% else %>
  <tbody>
    <% restaurant.items.each do |item| %>
      <% if item.active? %>
        <tr>
            <td><%= item.title %></td>
            <td><%= item.description %></td>
            <td>$<%= item.price %></td>
            <td><%= link_to 'Show Item', item_path(item), class:"btn btn-dark" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
<% end %>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1>Editing Restaurant</h1>

  <%= render 'form', restaurant: @restaurant %>

  <%= link_to 'Back', restaurants_path , class:"btn btn-secondary" %>

</div>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurants</h1>
  <table class="table text-center">
    <thead class="thead-dark">
      <tr>
        <th>Title</th>
        <th>Show</th>
        <% if current_user.admin? %>
          <th>No of Items</th>
          <th>Edit</th>
          <th>Delete</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <%= render @restaurants%>
    </tbody>
  </table>

  <%= link_to 'Back', root_path, class:"btn btn-dark"%>
  <% if current_user.admin? %>
    <%= link_to 'New Restaurant', new_restaurant_path, class:"btn btn-dark"%>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>New Restaurant</h1>

  <%= render partial: 'form' %>
  <%= link_to 'List', restaurants_path, class:"btn btn-dark"%>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1><%= @restaurant.title %></h1>
  <%= render 'table', restaurant: @restaurant %>
  <% if current_user.admin? %>
    <%= link_to 'New Item', new_item_path(restaurant_id: @restaurant.id), class:"btn btn-dark"%>
  <% end %>
  <%= link_to 'Back', restaurants_path, class:"btn btn-dark"%>
</div>