config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :items do
    get :top_items, on: :collection
  end

  resources :restaurants

  resources :categories do
    resources :items, only: %i[add_item delete_item] do
      member do
        post :add_item
        delete :delete_item
      end
    end
  end

  resource :carts, only: %i[show destroy] do
    resource :cart_items, only: %i[add_quantity reduce_quantity] do
      post :add_quantity
      post :reduce_quantity
      post :remove_item
      post :clear_cart
    end
  end

  resources :orders, except: %i[destroy] do
    resources :order_items, only: %i[add_item] do
      post :add_item
    end
  end

  root 'items#index'

  # api

  namespace :api do
    namespace :v1 do
      resources :items, only: %i[index show]
      resources :restaurants, only: %i[index]
      resources :categories, only: %i[index]
      resources :orders, only: %i[index]
    end
  end
end

app/models/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: categories
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ApplicationRecord
  has_many :category_items, dependent: :destroy
  has_many :items, through: :category_items

  validates :title, presence: true, uniqueness: true
end

app/controllers/api/v1/categories_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class CategoriesController < Api::V1::BaseController
      def index
        categories = Category.all
        render json: categories
      end
    end
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :find_category, except: %i[index new create]

  def index
    @categories = Category.all
    authorize @categories
  end

  def new
    @category = Category.new
    authorize @category
  end

  def show
    @items = Item.all
  end

  def create
    @category = Category.new(category_params)
    authorize @category
    if @category.save
      flash[:notice] = 'Category was successfully created'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Category was successfully updated'
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end

  def find_category
    @category = Category.find(params[:id])
    authorize @category
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/views/categories/_category.html.erb
<tr>
  <td><%= category.title %></td>
  <td><%= link_to 'Show Items', category_path(category), class:"btn btn-dark" %></td>
  <% if current_user.admin? %>
    <td><%= category.items.count %></td>
    <td><%= link_to 'Edit Category', edit_category_path(category), class:"btn btn-dark" %></td>
    <td><%= link_to 'Delete Category', category, method: :delete,
    data: { confirm: 'Are you sure?' } , class:"btn btn-dark" %></td>
  <% end %>
</tr>

app/views/categories/_form.html.erb
<%= form_with(model: @category, local: true) do |form| %>

  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize( @category.errors.count, "error" ) %> prohibited this Restaurant from being saved:
      </h2>

      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group pb-2">
    <%= form.text_field :title, class:"form-control", placeholder: 'Title', required: true %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-dark " %>
  </div>

<% end %>

app/views/categories/_table.html.erb
<div class="container">
  <table class="table text-center">
    <thead class="thead-dark">
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Description</th>
        <th>Price</th>
        <% if current_user.admin? %>
          <th>Status</th>
          <th>Drop</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% if category.items.count == 0%>
        <tr>
          <td class="colspan-4"><strong>No Items At the moment</strong></td>
        </tr>
      <% else %>
        <% category.items.each_with_index do |item, index| %>
          <tr>
            <td><%= index+1 %></td>
            <td><%= item.title %></td>
            <td><%= item.description %></td>
            <td>$<%= item.price %></td>
            <% if current_user.admin? %>
              <td><%= item.status %></td>
              <td><%= link_to 'Remove', delete_item_category_item_path(category.id, item.id), method: 'delete', class:"btn btn-dark"%></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categories/_table2.html.erb
<div class="container">
  <table class="table text-center">
    <thead class="thead-dark">
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Price</th>
        <th>Status</th>
        <th>Add</th>
      </tr>
    </thead>
    <tbody>
      <% items.each do |item| %>
        <% if !item.categories.include? category %>
          <tr>
            <td><%= item.title %></td>
            <td><%= item.description %></td>
            <td>$<%= item.price %></td>
            <td><%= item.status %></td>
            <td><%= link_to 'Add', add_item_category_item_path(category.id, item.id), method: 'post',  class:"btn btn-dark"%></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categories/edit.html.erb
<div class="container">
  <h1>Editing Category</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Back', categories_path , class:"btn btn-secondary" %>

</div>

app/views/categories/index.html.erb
<div class="container">
  <h1>Categories</h1>
  <table class="table text-center">
    <thead class="thead-dark">
      <tr>
        <th>Title</th>
        <th>Show</th>
        <% if current_user.admin? %>
          <th>No of Items</th>
          <th>Edit</th>
          <th>Delete</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <%= render @categories%>
    </tbody>
  </table>

  <%= link_to 'Back', root_path, class:"btn btn-dark"%>
  <% if current_user.admin? %>
    <%= link_to 'New Category', new_category_path, class:"btn btn-dark"%>
  <% end %>
</div>

app/views/categories/new.html.erb
<div class="container">
  <h1>New Category</h1>

  <%= render partial: 'form' %>
  <%= link_to 'List', categories_path, class:"btn btn-dark"%>
</div>

app/views/categories/show.html.erb
<div class="container">
  <h1 class = 'pt-5'><%= @category.title %> Items</h1>
  <%= render 'table', category: @category %>
  <% if current_user.admin? %>
    <h1 class = 'pt-5'>Add New Items to this Category </h1>
    <%= render 'table2', items: @items,category: @category %>
  <% end %>

  <%= link_to 'Back', categories_path, class:"btn btn-dark"%>
</div>