config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :items do
    get :top_items, on: :collection
  end

  resources :restaurants

  resources :categories do
    resources :items, only: %i[add_item delete_item] do
      member do
        post :add_item
        delete :delete_item
      end
    end
  end

  resource :carts, only: %i[show destroy] do
    resource :cart_items, only: %i[add_quantity reduce_quantity] do
      post :add_quantity
      post :reduce_quantity
      post :remove_item
      post :clear_cart
    end
  end

  resources :orders, except: %i[destroy] do
    resources :order_items, only: %i[add_item] do
      post :add_item
    end
  end

  root 'items#index'

  # api

  namespace :api do
    namespace :v1 do
      resources :items, only: %i[index show]
      resources :restaurants, only: %i[index]
      resources :categories, only: %i[index]
      resources :orders, only: %i[index]
    end
  end
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Dinner Dash', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if user_signed_in? %>
      <ul class="navbar-nav mr-auto">
        <% if current_user.user? %>
          <li class="nav-item active">
            <%= link_to carts_path(@current_cart), class: "btn btn-dark" do %>
              Cart <span class="badge badge-secondary"><%= @current_cart.items.count %></span>
            <% end %>
          </li>
        <% end %>
        <li class="nav-item active">
          <%= link_to 'Restaurants', restaurants_path, class: "nav-link"%>
        </li>
        <li class="nav-item active">
          <%= link_to 'Categories', categories_path, class: "nav-link"%>
        </li>
        <li class="nav-item active">
          <%= link_to 'Top Items', top_items_items_path	, class: "nav-link"%>
        </li>
        <li class="nav-item active">
          <%= link_to 'Orders', orders_path, class: "nav-link"%>
        </li>
        <% if current_user.admin? %>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">ADMIN</a>
          </li>
        <% end %>
        <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.user_name? %>
              <%= current_user.user_name %>
            <% else %>
              <%= current_user.first_name %>
            <% end %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li class="nav-item active">
            <%= link_to carts_path(@current_cart), class: "btn btn-dark" do %>
              Cart <span class="badge badge-secondary"><%= session[:cart_id].uniq.count %></span>
            <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
          </li>
        </ul>
    <% end %>
      <%= render 'items/search_form' %>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Dinnerdash</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <br>
      <% if notice%>
        <%= render 'layouts/alerts' %>
      <% end %>

      <br>
      <%= yield %>
    </div>
  </body>
</html>